packages:
  - packages/*
  - documentation

allowBuilds:
  es5-ext: true
  esbuild: true
  lefthook: true
  sharp: true
  workerd: true

minimumReleaseAge: 4320

patchedDependencies:
  starlight-llms-txt@0.10.0: patches/starlight-llms-txt@0.10.0.patch
