export const sidebar = [
  {
    label: "Learn",
    items: [
      { slug: "learn/quick-start" },
      { slug: "learn/installation" },
      { slug: "learn/typescript" },
      { slug: "learn/linting" },
      { slug: "learn/ai-tools" },
    ],
    collapsed: true,
  },
  {
    label: "Guides",
    items: [
      { slug: "guides" },
      { slug: "guides/optional" },
      { slug: "guides/mapping" },
      { slug: "guides/managing-tags" },
      { slug: "guides/nesting" },
      { slug: "guides/fallback" },
      { slug: "guides/guard" },
      { slug: "guides/code-splitting" },
      { slug: "guides/react" },
      { slug: "guides/vue" },
      { slug: "guides/debug" },
      { slug: "guides/observability" },
      { slug: "guides/graph" },
    ],
    collapsed: true,
  },
  {
    label: "Reference",
    items: [
      { slug: "reference" },
      { slug: "reference/compose" },
      { slug: "reference/create-task" },
      { slug: "reference/create-wire" },
      { slug: "reference/is" },
      { slug: "reference/literal" },
      { slug: "reference/optional" },
      { slug: "reference/shape" },
      { slug: "reference/tag" },
      { slug: "reference/types" },
    ],
    collapsed: true,
  },
  {
    label: "Coda",
    items: [
      { slug: "coda" },
      { slug: "coda/debug" },
      { slug: "coda/every" },
      { slug: "coda/not" },
      { slug: "coda/some" },
      { slug: "coda/when" },
    ],
    collapsed: true,
  },
  { slug: "community" },
  { slug: "sandbox" },
  { slug: "privacy" },
]
